#!/usr/bin/env bash
#Bash script that display information about subdomains
function one {
    array=('www' 'lb-01' 'web-01' 'web-02')
    for i in "${array[@]}"
    do
	result=$(dig "$i.$1" | grep -A1 'ANSWER SECTION:' | tail -1)
	RECORD_TYPE=$(echo "$result" | awk '{print $4}')
	DESTINATION=$(echo "$result" | awk '{print $5}')
	echo "The subdomain $i is a $RECORD_TYPE record and points to $DESTINATION"
    done
}

function two {
    result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -1)
    RECORD_TYPE=$(echo "$result" | awk '{print $4}')
    DESTINATION=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}
if [ $# -eq 1 ]; then
    one "$1"
elif [ $# -eq 2 ]; then
    two "$1" "$2"
fi
