#!/usr/bin/env bash
#Bash script that install and configure ngnix web server
sudo apt-get update
sudo apt-get -y install nginx
echo -e "<html>\n<body>\nHolberton School\n</body>\n</html>" >> /var/www/html/index.html
