#!/usr/bin/env bash
#Bash script that generates a MySQL dump and creates a compressed archive of it
mysqldump -u root -p "$1" --all-databases > backup.sql
c_date=$(date +'%d-%m-%Y')
tar -cvzf "$c_date.tar.gz" backup.sql
