#!/usr/bin/env bash
#Bash script that kills 4-to_infinity_and_beyond process.
process_to_kill="$(pgrep -f ./4-to_infinity_and_beyond)"
if [ -n "$process_to_kill" ]; then
    if [ "$process_to_kill" -gt 1000 ]; then
	kill "$process_to_kill"
    fi
fi
