#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely and I am invincible!!! when receiving a SIGTERM signal.
i=0
trap "echo I am invincible!!!" SIGTERM
while [ $i -eq 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
