#!/usr/bin/env bash
#Indefinitely writes I am alive! to the file /tmp/my/process
#In between every I am alive! message, the program should pause for 2 seconds.
i=0
while [ $i -eq 0 ]; do
    echo "I am alive!" > /tmp/my_process
    sleep 2
done
