#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times using the for loop
FILENAME="/etc/passwd"
if [ ! -e "$FILENAME" ]; then
    echo "$FILENAME file does not exist"
else
    if [ -f "$FILENAME" ]; then
	if [ -s "$FILENAME" ]; then
	    if [ -r "$FILENAME" ]; then
		while read -r line
		do
		    str="$(echo "$line" | cut -d ":" -f 1):"
		    str+="$(echo "$line" | cut -d ":" -f 3):"
		    str+="$(echo "$line" | cut -d ":" -f 6)"
		    echo "$str"
		done < "$FILENAME"
	    fi
	fi
    fi
fi
