#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using a format.
FILENAME="/etc/passwd"
if [ ! -e "$FILENAME" ]; then
    echo "$FILENAME file does not exist"
else
    if [ -f "$FILENAME" ]; then
	if [ -s "$FILENAME" ]; then
	    if [ -r "$FILENAME" ]; then
		while IFS=: read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND USER_ID PASSWORD USER_ID_INFO
		do
		    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
		done < "$FILENAME"
	    fi
	fi
    fi
fi
