#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.
FILENAME="$(pwd)/apache-access.log"
if [ ! -e "$FILENAME" ]; then
    echo "$FILENAME file does not exist"
else
    if [ -f "$FILENAME" ]; then
	if [ -s "$FILENAME" ]; then
	    if [ -r "$FILENAME" ]; then
		awk '{print $1,$9}' "$FILENAME"
	    fi
	fi
    fi
fi
