#!/usr/bin/env bash
#Bash script that loops from 1 to 10, and:
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
	echo "bad luck"
    elif [ $i -eq 8 ]; then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    i=$((i + 1))
done
