#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with some requirements.
FILENAME="/etc/hosts"
COPY="hosts.new"
if [ ! -e "$FILENAME" ]; then
    echo "$FILENAME file does not exist"
else
    if [ -f "$FILENAME" ]; then
	cp "$FILENAME" "$HOME/$COPY"
	sed -i 's/127.0.0.1/127.0.0.2/g' "$HOME/$COPY"
	echo -e "\n8.8.8.8\tfacebook.com" >> "$HOME/$COPY"
	cp -f "$HOME/$COPY" "$FILENAME"
    fi
fi
